version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - redis
      - mongodb
    ports:
      - "80:7000"
      - "8100:8100"
    image: nest_web
  mysql:
    container_name: nest-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
  redis:
    container_name: nest-redis
    image: redis:5.0
    ports:
      - "6379:6379"
  mongodb:
    container_name: nest-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rabong
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: chat
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo:/data/db
volumes:
  mongo:
  mysql: