version: "3.5"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: testNest:app
    depends_on:
      - mysql
      - redis
      - mongodb
    ports:
      - "80:7000"
  mysql:
    container_name: nest-mysql
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password1
      MYSQL_DATABASE: test
  redis:
    container_name: nest-redis
    image: redis:5.0
    ports:
      - "6379:6379"
  mongodb:
    container_name: nest-mongo
    image: mongo:4.4.12
    ports:
      - "27017:27017"
networks:
volumes:
